apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: skupper-operator-group
  namespace: pacman
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: pacman
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
