---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: pacman-skupper-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          online-boutique: "True"
