---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: skupperpacman-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: pacman-skupper-operator
              operator: In
              values:
                - "true"
